/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3449',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'background': '#0b1326',
        'on-background': '#dae2fd',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#e1bfbb',
        'primary': '#ffb4ac',
        'primary-container': '#991b1b',
        'on-primary': '#690007',
        'on-primary-container': '#ffaaa1',
        'inverse-primary': '#b02d29',
        'secondary': '#ffb77d',
        'secondary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#ffb77d',
        'secondary-container': '#d97707',
        'on-secondary': '#4d2600',
        'tertiary': '#94ccff',
        'tertiary-fixed': '#cde5ff',
        'tertiary-container': '#00527f',
        'outline': '#a88a86',
        'outline-variant': '#59413e',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-margin': '40px',
        'container-padding': '24px',
        'card-gap': '12px',
        'unit': '4px',
        'gutter': '16px',
      },
      fontFamily: {
        'headline-lg': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'display-case': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'title-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-caps': ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        'data-mono': ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
