/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#e9c349',
        'outline-variant': '#504532',
        'surface-bright': '#393939',
        'surface': '#131313',
        'on-secondary-fixed': '#241a00',
        'on-primary-fixed-variant': '#5c4300',
        'secondary-container': '#af8d11',
        'surface-container-low': '#1c1b1b',
        'on-surface': '#e5e2e1',
        'primary-fixed-dim': '#fbbc00',
        'on-primary-fixed': '#261a00',
        'surface-variant': '#353535',
        'on-secondary': '#3c2f00',
        'surface-tint': '#fbbc00',
        'background': '#131313',
        'on-tertiary-fixed': '#001f26',
        'on-error-container': '#ffdad6',
        'tertiary-container': '#04dcff',
        'on-secondary-fixed-variant': '#574500',
        'surface-container': '#20201f',
        'surface-container-high': '#2a2a2a',
        'on-primary-container': '#6d5000',
        'outline': '#9c8f78',
        'on-surface-variant': '#d4c5ab',
        'primary': '#ffe2ab',
        'tertiary': '#b4efff',
        'on-tertiary-fixed-variant': '#004e5c',
        'tertiary-fixed': '#aaedff',
        'surface-container-lowest': '#0e0e0e',
        'surface-dim': '#131313',
        'on-error': '#690005',
        'inverse-on-surface': '#313030',
        'error-container': '#93000a',
        'on-primary': '#402d00',
        'on-background': '#e5e2e1',
        'on-tertiary': '#003640',
        'on-tertiary-container': '#005d6d',
        'secondary': '#e9c349',
        'surface-container-highest': '#353535',
        'tertiary-fixed-dim': '#00d9fc',
        'error': '#ffb4ab',
        'primary-container': '#ffbf00',
        'inverse-primary': '#795900',
        'inverse-surface': '#e5e2e1',
        'primary-fixed': '#ffdfa0',
        'on-secondary-container': '#342800',
        'secondary-fixed': '#ffe088',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        'container-padding': '32px',
        'grid-gutter': '20px',
        'stack-gap': '16px',
      },
      fontFamily: {
        'title-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'mono-code': ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        'headline-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-base': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'display-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'mono-code': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-base': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
